Added Nqueensproblem
sigma3labs/Sigma3-DSA-Marathon pull request #55
Opened 2023-10-09 17:18 UTC by kashish-51

N-queens problem in a backtracking algorithm is a common programming task and is often used in coding interviews and aptitude tests to assess a candidate's problem-solving and algorithmic skills. The N-queens problem is a classic combinatorial problem in which you are asked to place N chess queens on an N×N chessboard in such a way that no two queens threaten each other. In other words, no two queens can be in the same row, column, or diagonal.

Solving the N-queens problem using backtracking is a popular approach because it efficiently explores the search space of possible solutions while pruning branches that are guaranteed to lead to invalid solutions. It's a good exercise for understanding and implementing backtracking algorithms and can be a valuable addition to your problem-solving toolkit.

2023-10-09 17:21 UTC, kashish-51 commented
Please Merge my code

2023-10-09 18:08 UTC, DEBADYUTI-KARMAKAR requested changes
add .java

2023-10-09 18:19 UTC, kashish-51 commented
added .java

2023-10-10 07:13 UTC, DEBADYUTI-KARMAKAR approved these changes

2023-10-10 07:14 UTC, merged